---
# handlers for ansible-role-systemd-networkd

- name: Restart systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  when: systemd_networkd_apply_config
